mod 'boxen',    '3.3.0', :github_tarball => 'boxen/puppet-boxen'
mod 'homebrew', '1.0.0', :github_tarball => 'boxen/puppet-homebrew'
mod 'stdlib',   '4.0.0', :github_tarball => 'puppetlabs/puppetlabs-stdlib'
